version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine # Utilise une image Node.js Alpine
    steps:
      - checkout # Récupère le code source
      - run:
          name: Install dependencies
          command: npm install # Installe les dépendances

  # Job pour construire l'image Docker
  docker_build:
    docker:
      - image: docker:19.03.12 # Utilise une image Docker pour construire l'image Docker
    steps:
      - checkout # Récupère le code source
      - setup_remote_docker # Configure Docker
      - run:
          name: Build Docker image
          command: |
            docker build -t node-app:latest . # Construit l'image Docker
            docker tag node-app:latest ethokia/ema-nodejs-app:latest # Ajoute une étiquette à l'image
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Connecte à Docker Hub
            docker push ethokia/ema-nodejs-app:latest # Pousse l'image sur Docker Hub

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build